# Generated by Django 2.1.5 on 2019-01-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_link', models.TextField()),
                ('facility_name', models.TextField()),
                ('notice_html', models.TextField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
