# Generated by Django 2.1.5 on 2019-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190120_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.TextField()),
                ('facility_link', models.TextField()),
                ('html_content', models.TextField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
