# Generated by Django 2.1.5 on 2019-01-21 00:51

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190120_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('facility_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None)),
                ('key', models.UUIDField(default=uuid.uuid1, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='facility_link',
        ),
        migrations.RemoveField(
            model_name='status',
            name='facility_name',
        ),
        migrations.AddField(
            model_name='status',
            name='facility_id',
            field=models.CharField(default='bad', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
