# Generated by Django 2.1.5 on 2019-01-25 01:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190121_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='facility_ids',
        ),
        migrations.AddField(
            model_name='status',
            name='facility_name',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='facility_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
