# Generated by Django 2.1.5 on 2019-01-26 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190125_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='facility_link',
            field=models.TextField(default=datetime.datetime(2019, 1, 26, 2, 59, 19, 793352, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
